### PR TITLE
support/require time 1.5, helps build ssh with ghc 7.10

### PR DESCRIPTION
**Pull request by simonmichael**

### CODE REVIEW

**Comment by mauke** [comment]
What does ssh have to do with ghc?

**Comment by hsenag** [comment]
The 'ssh' package on hackage currently depends on pseudomacros. I do have a local change that switches to CPP instead though so could do that instead if necessary.

**Comment by mauke** [comment]
Ah, this isn't apparent from http://hackage.haskell.org/package/ssh. Unfortunately I can't reproduce the problem because:

```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: ssh-0.3.0.1 (user goal)
next goal: base (dependency of ssh-0.3.0.1)
rejecting: base-4.8.0.0/installed-fc6... (conflict: base =>
integer-gmp==1.0.0.0/installed-c95..., ssh => integer-gmp>=0.5 && <0.6)
rejecting: base-4.8.0.0, 4.7.0.2, 4.7.0.1, 4.7.0.0, 4.6.0.1, 4.6.0.0, 4.5.1.0,
4.5.0.0, 4.4.1.0, 4.4.0.0, 4.3.1.0, 4.3.0.0, 4.2.0.2, 4.2.0.1, 4.2.0.0,
4.1.0.0, 4.0.0.0, 3.0.3.2, 3.0.3.1 (global constraint requires installed
instance)
Dependency tree exhaustively searched.
```

**Comment by simonmichael** [comment]
The point of this PR is to let this package build with time 1.5+, I mentioned ssh and ghc 7.10 only for context.

(This PR also drops support for time < 1.5; to keep that, I think you'd need to add a module, since CPP can't be used in  PseudoMacros.hs.)

**Comment by mauke** [comment]
D'oh. Of course I can just try to build `pseudomacros` itself, now that I have a modern ghc.

I didn't see the point of changing the version numbering scheme and adding a new file, so I just uploaded a new version without those.

**Comment by simonmichael** [comment]
Thanks! Consider adding the changelog next time. I really appreciate changelogs when troubleshooting dependency issues.

**Pull request closed without merging**
